/**
 * Ethiroli SaaS Platform — Centralized Permissions Registry
 * Direct mapping of capabilities based on PROJECT_DOCUMENTATION.md Section 5.2 Permission Matrix.
 */

import { ROLES } from './roleRouting.js';

export const PERMISSIONS = Object.freeze({
  // Users & System
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_AUDIT_LOGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_SETTINGS: [ROLES.SUPER_ADMIN],
  MANAGE_TENANTS: [ROLES.SUPER_ADMIN],
  GLOBAL_SEARCH: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // CRM & Leads
  VIEW_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.SALES],
  EDIT_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.SALES],
  DELETE_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // HRMS
  MANAGE_EMPLOYEES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  MANAGE_INTERNS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  VIEW_ALL_ATTENDANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION],
  MANAGE_LEAVES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION],
  PROCESS_PAYROLL: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.FINANCE],
  CONDUCT_INTERVIEWS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],

  // LMS
  MANAGE_COURSES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  GRADE_SUBMISSIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  TAKE_COURSES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STUDENT, ROLES.TUTOR],

  // Finance
  MANAGE_FINANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],
  VIEW_INVOICES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE, ROLES.PROJECT_MANAGER],

  // PMS
  MANAGE_CLIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],
  MANAGE_SUBSCRIPTIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],
  MANAGE_TASKS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER, ROLES.EMPLOYEE, ROLES.INTERN],

  // Developer & Monitoring
  DEVELOPER_PORTAL: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SYSTEM_MONITORING: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  AUTOMATION_STUDIO: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
});

/**
 * Checks if a user has a specific permission capability
 * @param {Object} user - User object containing `role`
 * @param {string} permissionKey - Key from PERMISSIONS
 * @returns {boolean}
 */
export const hasPermission = (user, permissionKey) => {
  if (!user || !user.role) return false;
  const allowed = PERMISSIONS[permissionKey];
  if (!allowed) return false;
  return allowed.includes(String(user.role).trim().toUpperCase());
};

export default {
  PERMISSIONS,
  hasPermission,
};
