/**
 * Ethiroli SaaS Platform — Centralized Permissions Registry
 * Direct mapping of capabilities based on PROJECT_DOCUMENTATION.md Section 5.2 Permission Matrix.
 */

import { ROLES } from './roleRouting.js';

export const PERMISSIONS = Object.freeze({
  // 1. Auth & User Management
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_OWN_PROFILE: Object.values(ROLES),

  // 2. CRM & Leads
  VIEW_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.SALES],
  EDIT_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.SALES],
  DELETE_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FOLLOW_UP_LEADS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.SALES],

  // 3. HRMS
  MANAGE_EMPLOYEES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  MANAGE_INTERNS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  VIEW_ALL_ATTENDANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION],
  LOG_OWN_ATTENDANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION, ROLES.EMPLOYEE],
  MANAGE_LEAVES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION],
  REQUEST_OWN_LEAVE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.RECEPTION, ROLES.EMPLOYEE],
  PROCESS_PAYROLL: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.FINANCE],
  VIEW_OWN_PAYSLIP: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.FINANCE, ROLES.EMPLOYEE],
  PERFORMANCE_REVIEWS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.EMPLOYEE],
  CONDUCT_INTERVIEWS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],

  // 4. LMS
  MANAGE_COURSES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  MANAGE_CURRICULUM: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  VIEW_ENROLLMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  TAKE_QUIZZES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STUDENT, ROLES.TUTOR],
  GRADE_SUBMISSIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR],
  FORUM_ACCESS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR, ROLES.STUDENT],
  LIVE_QUIZ_HOSTING: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR, ROLES.STUDENT],
  BADGES_CERTIFICATES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR, ROLES.STUDENT],

  // 5. Finance
  VIEW_FINANCES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],
  MANAGE_INVOICES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],
  TRACK_PAYMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],
  RECURRING_SCHEDULES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],
  PAYROLL_RUNS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],

  // 6. PMS
  MANAGE_CLIENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],
  MANAGE_SUBSCRIPTIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],
  MANAGE_TASKS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER, ROLES.EMPLOYEE, ROLES.INTERN],
  PMS_INVOICES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],
  COMPANY_SETTINGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROJECT_MANAGER],

  // 7. System & Operations
  VIEW_AUDIT_LOGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_SETTINGS: [ROLES.SUPER_ADMIN],
  MANAGE_INTEGRATIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SYSTEM_MONITORING: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  CALENDAR_ACCESS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.TUTOR, ROLES.PROJECT_MANAGER, ROLES.FINANCE, ROLES.RECEPTION, ROLES.EMPLOYEE, ROLES.INTERN],
  MANAGE_HOLIDAYS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  APPROVE_WORKFLOWS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.PROJECT_MANAGER, ROLES.EMPLOYEE],
  GLOBAL_SEARCH: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // 8. Multi-Tenant & Marketplace
  MANAGE_TENANTS: [ROLES.SUPER_ADMIN],
  MARKETPLACE_ACCESS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.STUDENT],
  VIEW_REPORTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.FINANCE],

  // 9. Developer Tools
  DEVELOPER_PORTAL: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  WEBHOOKS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  AUTOMATION_STUDIO: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  AI_ANALYTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
});

/**
 * Checks if a user has a specific permission capability
 * @param {Object} user - User object containing `role`
 * @param {string} permissionKey - Key from PERMISSIONS
 * @returns {boolean}
 */
export const hasPermission = (user, permissionKey) => {
  if (!user || !user.role) return false;
  const allowed = PERMISSIONS[permissionKey];
  if (!allowed) return false;
  return allowed.includes(String(user.role).trim().toUpperCase());
};

export default {
  PERMISSIONS,
  hasPermission,
};
