export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  HR: 'HR',
  TUTOR: 'TUTOR',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  FINANCE: 'FINANCE',
  SALES: 'SALES',
  RECEPTION: 'RECEPTION',
  EMPLOYEE: 'EMPLOYEE',
  STUDENT: 'STUDENT',
  INTERN: 'INTERN'
};

export const LEAD_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  DEMO: 'DEMO',
  COUNSELLING: 'COUNSELLING',
  ADMISSION: 'ADMISSION',
  PAYMENT: 'PAYMENT',
  LOST: 'LOST'
};

export const SOURCES = {
  WEBSITE: 'WEBSITE',
  REFERRAL: 'REFERRAL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  WALK_IN: 'WALK_IN',
  PHONE: 'PHONE',
  INDEED: 'INDEED',
  OTHER: 'OTHER'
};
