export const ROLE_NAVIGATION = Object.freeze({
  SUPER_ADMIN: [
    { label: 'Dashboard', path: '/app/super-admin/dashboard', icon: 'dashboard' },
    {
      label: 'Platform',
      icon: 'domain',
      children: [
        { label: 'Tenants / Organizations', path: '/app/super-admin/tenants', icon: 'domain' },
        { label: 'Users', path: '/app/super-admin/users', icon: 'group' },
        { label: 'Roles & Permissions', path: '/app/super-admin/roles-permissions', icon: 'admin_panel_settings' },
        { label: 'Subscriptions & Plans', path: '/app/super-admin/plans', icon: 'subscriptions' },
        { label: 'Platform Billing', path: '/app/super-admin/billing', icon: 'payments' },
      ],
    },
    {
      label: 'CRM',
      icon: 'contact_mail',
      children: [
        { label: 'Leads (CRM)', path: '/app/super-admin/leads', icon: 'contact_mail' },
      ],
    },
    {
      label: 'Operations',
      icon: 'calendar_month',
      children: [
        { label: 'Global Calendar', path: '/app/super-admin/calendar', icon: 'calendar_month' },
        { label: 'Approvals', path: '/app/super-admin/approvals', icon: 'verified' },
        { label: 'Notifications', path: '/app/super-admin/notifications', icon: 'notifications' },
        { label: 'Communications', path: '/app/super-admin/communications', icon: 'forum' },
      ],
    },
    {
      label: 'Platform Services',
      icon: 'smart_toy',
      children: [
        { label: 'Automation Studio', path: '/app/super-admin/automation', icon: 'smart_toy' },
        { label: 'Integrations', path: '/app/super-admin/integrations', icon: 'hub' },
        { label: 'Email / SMS / WhatsApp', path: '/app/super-admin/messaging', icon: 'sms' },
        { label: 'Developer Portal', path: '/app/super-admin/developer', icon: 'code' },
        { label: 'Marketplace', path: '/app/super-admin/marketplace', icon: 'storefront' },
      ],
    },
    {
      label: 'Analytics',
      icon: 'bar_chart',
      children: [
        { label: 'Reports', path: '/app/super-admin/reports', icon: 'bar_chart' },
        { label: 'AI Analytics', path: '/app/super-admin/analytics', icon: 'analytics' },
        { label: 'Gamification', path: '/app/super-admin/gamification', icon: 'emoji_events' },
      ],
    },
    {
      label: 'System',
      icon: 'monitor_heart',
      children: [
        { label: 'System Monitoring', path: '/app/super-admin/monitoring', icon: 'monitor_heart' },
        { label: 'System Search', path: '/app/super-admin/system-search', icon: 'search' },
        { label: 'Feature Flags', path: '/app/super-admin/feature-flags', icon: 'toggle_on' },
        { label: 'System Configuration', path: '/app/super-admin/configuration', icon: 'tune' },
        { label: 'Database / Storage', path: '/app/super-admin/storage', icon: 'storage' },
        { label: 'Backup & Recovery', path: '/app/super-admin/backups', icon: 'backup' },
      ],
    },
    {
      label: 'Security',
      icon: 'security',
      children: [
        { label: 'Security Center', path: '/app/super-admin/security', icon: 'security' },
        { label: 'Audit Logs', path: '/app/super-admin/audit-logs', icon: 'history' },
      ],
    },
    {
      label: 'Administration',
      icon: 'settings',
      children: [
        { label: 'Settings', path: '/app/super-admin/settings', icon: 'settings' },
        { label: 'Admin Profile', path: '/app/super-admin/profile', icon: 'person' },
      ],
    },
  ],
  ADMIN: [
    { label: 'Dashboard', path: '/app/admin/dashboard', icon: 'dashboard' },
    { label: 'People', path: '/app/admin/people', icon: 'group', children: [
      { label: 'Employees', path: '/app/admin/employees', icon: 'badge' },
      { label: 'Interns', path: '/app/admin/interns', icon: 'school' },
      { label: 'Students', path: '/app/admin/students', icon: 'school' },
      { label: 'Tutors', path: '/app/admin/tutors', icon: 'school' },
    ]},
    { label: 'Learning', path: '/app/admin/learning', icon: 'menu_book', children: [
      { label: 'Courses', path: '/app/admin/courses', icon: 'menu_book' },
      { label: 'Curriculum', path: '/app/admin/curriculum', icon: 'library_books' },
      { label: 'Assignments', path: '/app/admin/assignments', icon: 'assignment' },
      { label: 'Batches', path: '/app/admin/batches', icon: 'groups' },
      { label: 'Training', path: '/app/admin/training', icon: 'school' },
    ]},
    { label: 'Projects', path: '/app/admin/projects', icon: 'code', children: [
      { label: 'Projects', path: '/app/admin/projects', icon: 'code' },
      { label: 'Tasks', path: '/app/admin/tasks', icon: 'checklist' },
      { label: 'Teams', path: '/app/admin/teams', icon: 'groups' },
    ]},
    { label: 'HR', path: '/app/admin/hr', icon: 'badge', children: [
      { label: 'Attendance', path: '/app/admin/attendance', icon: 'schedule' },
      { label: 'Leaves', path: '/app/admin/leaves', icon: 'event_busy' },
      { label: 'Performance', path: '/app/admin/performance', icon: 'trending_up' },
      { label: 'Payroll', path: '/app/admin/payroll', icon: 'payments' },
    ]},
    { label: 'CRM', path: '/app/admin/crm', icon: 'contact_mail', children: [
      { label: 'Leads', path: '/app/admin/leads', icon: 'contact_mail' },
      { label: 'Contacts', path: '/app/admin/contacts', icon: 'person' },
      { label: 'Follow-ups', path: '/app/admin/follow-ups', icon: 'notification_important' },
      { label: 'Deals', path: '/app/admin/deals', icon: 'deal' },
    ]},
    { label: 'Finance', path: '/app/admin/finance', icon: 'payments', children: [
      { label: 'Income', path: '/app/admin/income', icon: 'trending_up' },
      { label: 'Expenses', path: '/app/admin/expenses', icon: 'trending_down' },
      { label: 'Invoices', path: '/app/admin/invoices', icon: 'receipt_long' },
      { label: 'Payments', path: '/app/admin/payments', icon: 'paid' },
    ]},
    { label: 'Reports', path: '/app/admin/reports', icon: 'bar_chart' },
    { label: 'Notifications', path: '/app/admin/notifications', icon: 'notifications' },
    { label: 'Documents', path: '/app/admin/documents', icon: 'folder' },
    { label: 'Integrations', path: '/app/admin/integrations', icon: 'hub' },
    { label: 'Calendar', path: '/app/admin/calendar', icon: 'calendar_month' },
    { label: 'Calendar Types', path: '/app/admin/calendar/types', icon: 'tune' },
    { label: 'Audit Logs', path: '/app/admin/audit-logs', icon: 'history' },
    { label: 'Settings', path: '/app/admin/settings', icon: 'settings' },
  ],
  HR: [
    { label: 'Dashboard', path: '/app/hr/dashboard', icon: 'dashboard' },
    { label: 'Job Applications', path: '/app/hr/applications', icon: 'person_lines_fill' },
    { label: 'Website Inquiries', path: '/app/hr/inquiries', icon: 'contact_mail' },
    { label: 'Employees', path: '/app/hr/employees', icon: 'badge' },
    { label: 'Interns', path: '/app/hr/interns', icon: 'school' },
    { label: 'Onboarding', path: '/app/hr/onboarding', icon: 'person_add' },
    { label: 'Attendance', path: '/app/hr/attendance', icon: 'schedule' },
    { label: 'Calendar', path: '/app/hr/calendar', icon: 'calendar_month' },
    { label: 'Leaves', path: '/app/hr/leaves', icon: 'event_busy' },
    { label: 'Interviews', path: '/app/hr/interviews', icon: 'record_voice_over' },
    { label: 'Training', path: '/app/hr/training', icon: 'school' },
    { label: 'Performance', path: '/app/hr/performance', icon: 'trending_up' },
    { label: 'Payroll', path: '/app/hr/payroll', icon: 'payments' },
    { label: 'Documents', path: '/app/hr/documents', icon: 'folder' },
    { label: 'Announcements', path: '/app/hr/announcements', icon: 'campaign' },
    { label: 'Jobs Board', path: '/app/hr/jobs-board', icon: 'work' },
    { label: 'Exit / Offboarding', path: '/app/hr/offboarding', icon: 'exit_to_app' },
    { label: 'HR Reports', path: '/app/hr/reports', icon: 'bar_chart' },
  ],
  TUTOR: [
    { label: 'Dashboard', path: '/app/tutor/dashboard', icon: 'dashboard' },
    { label: 'Courses', path: '/app/tutor/courses', icon: 'menu_book' },
    { label: 'Curriculum', path: '/app/tutor/curriculum', icon: 'library_books' },
    { label: 'Students', path: '/app/tutor/students', icon: 'groups' },
    { label: 'Attendance', path: '/app/tutor/attendance', icon: 'schedule' },
    { label: 'Calendar', path: '/app/tutor/calendar', icon: 'calendar_month' },
    { label: 'Assignments', path: '/app/tutor/assignments', icon: 'assignment' },
    { label: 'Quizzes', path: '/app/tutor/quizzes', icon: 'quiz' },
    { label: 'Question Bank', path: '/app/tutor/question-bank', icon: 'help_outline' },
    { label: 'Grades', path: '/app/tutor/grades', icon: 'grade' },
    { label: 'Doubt Management', path: '/app/tutor/doubts', icon: 'help' },
    { label: 'Certificates', path: '/app/tutor/certificates', icon: 'workspace_premium' },
    { label: 'Course Analytics', path: '/app/tutor/analytics', icon: 'analytics' },
    { label: 'Forum', path: '/app/tutor/forum', icon: 'forum' },
    { label: 'Communications', path: '/app/tutor/communications', icon: 'mail' },
  ],
  PROJECT_MANAGER: [
    { label: 'Dashboard', path: '/app/pm/dashboard', icon: 'dashboard' },
    { label: 'Projects', path: '/app/pm/projects', icon: 'code' },
    { label: 'Team', path: '/app/pm/team', icon: 'groups' },
    { label: 'Tasks', path: '/app/pm/tasks', icon: 'checklist' },
    { label: 'Timesheets', path: '/app/pm/timesheets', icon: 'schedule' },
    { label: 'Client Communication', path: '/app/pm/client-comms', icon: 'chat' },
    { label: 'Invoices', path: '/app/pm/invoices', icon: 'receipt_long' },
    { label: 'Project Reports', path: '/app/pm/reports', icon: 'bar_chart' },
    { label: 'Approvals', path: '/app/pm/approvals', icon: 'verified' },
    { label: 'Calendar', path: '/app/pm/calendar', icon: 'calendar_month' },
    { label: 'Company Settings', path: '/app/pm/settings', icon: 'business' },
  ],
  FINANCE: [
    { label: 'Dashboard', path: '/app/finance/dashboard', icon: 'dashboard' },
    { label: 'Customers / Clients', path: '/app/finance/clients', icon: 'groups' },
    { label: 'Salary', path: '/app/finance/salary', icon: 'payments' },
    { label: 'Tax', path: '/app/finance/tax', icon: 'receipt_long' },
    { label: 'Refunds', path: '/app/finance/refunds', icon: 'undo' },
    { label: 'Receivables', path: '/app/finance/receivables', icon: 'monetization_on' },
    { label: 'Payables', path: '/app/finance/payables', icon: 'paid' },
    { label: 'Financial Reports', path: '/app/finance/reports', icon: 'bar_chart' },
    { label: 'Income', path: '/app/finance/income', icon: 'trending_up' },
    { label: 'Expenses', path: '/app/finance/expenses', icon: 'trending_down' },
    { label: 'Invoices', path: '/app/finance/invoices', icon: 'receipt_long' },
    { label: 'Payments', path: '/app/finance/payments', icon: 'paid' },
    { label: 'Calendar', path: '/app/finance/calendar', icon: 'calendar_month' },
    { label: 'Schedules', path: '/app/finance/schedules', icon: 'update' },
    { label: 'Payroll Runs', path: '/app/finance/payroll', icon: 'payments' },
  ],
  SALES: [
    { label: 'Dashboard', path: '/app/sales/dashboard', icon: 'dashboard' },
    { label: 'CRM Contacts', path: '/app/sales/contacts', icon: 'contact_mail' },
    { label: 'Opportunities', path: '/app/sales/opportunities', icon: 'trending_up' },
    { label: 'Deals', path: '/app/sales/deals', icon: 'deal' },
    { label: 'Proposals / Quotes', path: '/app/sales/proposals', icon: 'description' },
    { label: 'Calendar', path: '/app/sales/calendar', icon: 'calendar_month' },
    { label: 'Campaigns', path: '/app/sales/campaigns', icon: 'campaign' },
    { label: 'Reports', path: '/app/sales/reports', icon: 'bar_chart' },
    { label: 'Follow-Ups', path: '/app/sales/follow-ups', icon: 'notification_important' },
  ],
  RECEPTION: [
    { label: 'Dashboard', path: '/app/reception/dashboard', icon: 'dashboard' },
    { label: 'Visitors', path: '/app/reception/visitors', icon: 'person' },
    { label: 'Enquiries', path: '/app/reception/enquiries', icon: 'forum' },
    { label: 'Admissions', path: '/app/reception/admissions', icon: 'school' },
    { label: 'Student / Intern Registration', path: '/app/reception/registration', icon: 'person_add' },
    { label: 'Payments', path: '/app/reception/payments', icon: 'paid' },
    { label: 'Calendar', path: '/app/reception/calendar', icon: 'calendar_month' },
    { label: 'Communications', path: '/app/reception/communications', icon: 'mail' },
  ],
  EMPLOYEE: [
    { label: 'Dashboard', path: '/app/employee/dashboard', icon: 'dashboard' },
    { label: 'Attendance', path: '/app/employee/attendance', icon: 'schedule' },
    { label: 'My Profile', path: '/app/employee/profile', icon: 'person' },
    { label: 'Documents', path: '/app/employee/documents', icon: 'folder' },
    { label: 'Salary', path: '/app/employee/salary', icon: 'payments' },
    { label: 'Training', path: '/app/employee/training', icon: 'school' },
    { label: 'Announcements', path: '/app/employee/announcements', icon: 'campaign' },
    { label: 'Help / Support', path: '/app/employee/support', icon: 'help' },
    { label: 'My Tasks', path: '/app/employee/tasks', icon: 'checklist' },
    { label: 'Calendar', path: '/app/employee/calendar', icon: 'calendar_month' },
    { label: 'Approvals', path: '/app/employee/approvals', icon: 'verified' },
    { label: 'Leaves', path: '/app/employee/leaves', icon: 'event_busy' },
    { label: 'Payslips', path: '/app/employee/payslips', icon: 'receipt' },
    { label: 'Performance', path: '/app/employee/performance', icon: 'trending_up' },
  ],
  STUDENT: [
    { label: 'Dashboard', path: '/app/student/dashboard', icon: 'dashboard' },
    { label: 'My Courses', path: '/app/student/courses', icon: 'menu_book' },
    { label: 'Course Modules', path: '/app/student/modules', icon: 'library_books' },
    { label: 'Course Player', path: '/app/student/course-player', icon: 'play_circle' },
    { label: 'Live Classes', path: '/app/student/live-classes', icon: 'video_call' },
    { label: 'Live Quiz', path: '/app/student/live-quiz', icon: 'quiz' },
    { label: 'Calendar', path: '/app/student/calendar', icon: 'calendar_month' },
    { label: 'Assessments', path: '/app/student/quiz', icon: 'assignment' },
    { label: 'Assignments', path: '/app/student/assignments', icon: 'assignment' },
    { label: 'Projects', path: '/app/student/projects', icon: 'code' },
    { label: 'Attendance', path: '/app/student/attendance', icon: 'schedule' },
    { label: 'Doubts', path: '/app/student/doubts', icon: 'help' },
    { label: 'Messages', path: '/app/student/messages', icon: 'mail' },
    { label: 'Mind Map', path: '/app/student/mindmap', icon: 'account_tree' },
    { label: 'Certificates', path: '/app/student/certificates', icon: 'workspace_premium' },
    { label: 'Documents', path: '/app/student/documents', icon: 'folder' },
    { label: 'Payments', path: '/app/student/payments', icon: 'paid' },
    { label: 'Notifications', path: '/app/student/notifications', icon: 'notifications' },
    { label: 'Profile', path: '/app/student/profile', icon: 'person' },
  ],
  INTERN: [
    { label: 'Dashboard', path: '/app/intern/dashboard', icon: 'dashboard' },
    { label: 'My Training Plan', path: '/app/intern/training-plan', icon: 'route' },
    { label: 'Daily Tasks', path: '/app/intern/tasks', icon: 'checklist' },
    { label: 'Attendance', path: '/app/intern/attendance', icon: 'schedule' },
    { label: 'Projects', path: '/app/intern/projects', icon: 'code' },
    { label: 'Assignments', path: '/app/intern/assignments', icon: 'assignment' },
    { label: 'Daily Work Log', path: '/app/intern/work-log', icon: 'edit_note' },
    { label: 'Mentor', path: '/app/intern/mentor', icon: 'person' },
    { label: 'Feedback', path: '/app/intern/feedback', icon: 'rate_review' },
    { label: 'Calendar', path: '/app/intern/calendar', icon: 'calendar_month' },
    { label: 'Documents', path: '/app/intern/documents', icon: 'folder' },
    { label: 'Certificate', path: '/app/intern/certificate', icon: 'workspace_premium' },
  ],
});

export function getNavigationForRole(role) {
  if (!role) return [];
  const normalized = String(role).trim().toUpperCase();
  return ROLE_NAVIGATION[normalized] || [];
}
