import React, { useState } from 'react';
import AdminPage from '../../../common/components/AdminPage/AdminPage.jsx';
import { useModalDismiss, backdropClick } from '../components/useModalDismiss.js';
import ShareBar from '../components/ShareBar.jsx';
import { downloadDataUri, safeFilename } from '../components/documentActions.js';

/**
 * Builds an inline SVG "page" for the on-screen preview.
 *
 * Returned as a data URI so it renders as a real image in an <img>, which
 * keeps the preview styled as a document page without shipping binary assets.
 */
const buildPreviewImage = (doc) => {
  const esc = (s) =>
    String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const title = esc(doc.title);
  // Wrap the title onto up to three lines so long document names stay readable.
  const words = title.split(' ');
  const lines = [];
  let current = '';
  for (const w of words) {
    if ((current + ' ' + w).trim().length > 34) {
      lines.push(current.trim());
      current = w;
      if (lines.length === 2) break;
    } else {
      current = `${current} ${w}`;
    }
  }
  if (current.trim() && lines.length < 3) lines.push(current.trim());

  const body = lines
    .map((l, i) => `<text x="60" y="${168 + i * 30}" font-family="Segoe UI, Arial, sans-serif" font-size="21" font-weight="700" fill="#1e293b">${l}</text>`)
    .join('');

  const desc = esc(doc.description || '');
  const descWords = desc.split(' ');
  const descLines = [];
  let dcur = '';
  for (const w of descWords) {
    if ((dcur + ' ' + w).trim().length > 58) {
      descLines.push(dcur.trim());
      dcur = w;
      if (descLines.length === 3) break;
    } else {
      dcur = `${dcur} ${w}`;
    }
  }
  if (dcur.trim() && descLines.length < 3) descLines.push(dcur.trim());

  const descBody = descLines
    .map((l, i) => `<text x="60" y="${300 + i * 24}" font-family="Segoe UI, Arial, sans-serif" font-size="15" fill="#64748b">${l}</text>`)
    .join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="680" height="920" viewBox="0 0 680 920">
  <rect width="680" height="920" fill="#f8fafc"/>
  <rect x="0" y="0" width="680" height="8" fill="#f4a261"/>
  <rect x="40" y="44" width="600" height="76" rx="10" fill="#ffffff" stroke="#e2e8f0"/>
  <circle cx="82" cy="82" r="20" fill="#f4a261" fill-opacity="0.16"/>
  <text x="82" y="89" font-family="Segoe UI, Arial, sans-serif" font-size="18" font-weight="700" fill="#f4a261" text-anchor="middle">E</text>
  <text x="118" y="76" font-family="Segoe UI, Arial, sans-serif" font-size="17" font-weight="700" fill="#1e293b">Ethiroli</text>
  <text x="118" y="98" font-family="Segoe UI, Arial, sans-serif" font-size="13" fill="#94a3b8">${esc(doc.categoryLabel || 'Document')}</text>
  <text x="618" y="88" font-family="Segoe UI, Arial, sans-serif" font-size="14" font-weight="700" fill="#64748b" text-anchor="end">${esc(doc.format)}</text>
  ${body}
  <rect x="60" y="${312 + descLines.length * 24}" width="180" height="10" rx="5" fill="#e2e8f0"/>
  ${descBody}
  <rect x="40" y="600" width="600" height="120" rx="10" fill="#ffffff" stroke="#e2e8f0"/>
  <text x="60" y="632" font-family="Segoe UI, Arial, sans-serif" font-size="12" font-weight="700" fill="#94a3b8" letter-spacing="1">DOCUMENT DETAILS</text>
  <text x="60" y="662" font-family="Segoe UI, Arial, sans-serif" font-size="14" fill="#475569">Format: ${esc(doc.format)}</text>
  <text x="60" y="686" font-family="Segoe UI, Arial, sans-serif" font-size="14" fill="#475569">File size: ${esc(doc.size)}</text>
  <text x="360" y="662" font-family="Segoe UI, Arial, sans-serif" font-size="14" fill="#475569">Updated: ${esc(doc.updatedAt)}</text>
  <text x="360" y="686" font-family="Segoe UI, Arial, sans-serif" font-size="14" fill="#475569">Status: ${esc(doc.status.replace(/_/g, ' ').toLowerCase())}</text>
  <rect x="40" y="756" width="600" height="120" rx="10" fill="#ffffff" stroke="#e2e8f0"/>
  <text x="60" y="788" font-family="Segoe UI, Arial, sans-serif" font-size="12" font-weight="700" fill="#94a3b8" letter-spacing="1">AUTHORISED SIGNATURE</text>
  <path d="M78 838 q26 -34 44 -6 q16 -30 34 2 q20 26 44 -10" fill="none" stroke="#334155" stroke-width="3" stroke-linecap="round"/>
  <line x1="60" y1="858" x2="280" y2="858" stroke="#cbd5e1" stroke-width="2"/>
  <text x="60" y="872" font-family="Segoe UI, Arial, sans-serif" font-size="11" fill="#94a3b8">Authorised signatory</text>
  <text x="620" y="900" font-family="Segoe UI, Arial, sans-serif" font-size="11" fill="#cbd5e1" text-anchor="end">Preview generated by Ethiroli IMS</text>
</svg>`;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
};

export default function Documents() {
  const [activeCategory, setActiveCategory] = useState('ALL');
  const [alert, setAlert] = useState({ type: '', text: '' });
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [uploadDocType, setUploadDocType] = useState('COLLEGE_NOC');
  // Document shown in the on-screen preview overlay.
  const [previewDoc, setPreviewDoc] = useState(null);

  // Escape + scroll-lock for both dialogs. The previous onKeyDown handlers sat
  // on the overlay div, which never takes focus, so they rarely fired.
  useModalDismiss(showUploadModal, () => setShowUploadModal(false));
  useModalDismiss(!!previewDoc, () => setPreviewDoc(null));

  const documents = [
    // Internship Documents
    {
      id: 'doc-1',
      title: 'Official Internship Offer Letter & Appointment',
      category: 'INTERNSHIP',
      categoryLabel: 'Internship',
      format: 'PDF',
      size: '1.4 MB',
      updatedAt: 'May 10, 2026',
      status: 'VERIFIED',
      description: 'Official offer letter detailing stipend, terms, duration, and mentor allocation.'
    },
    {
      id: 'doc-2',
      title: 'Signed Non-Disclosure Agreement (NDA) & IP Policy',
      category: 'INTERNSHIP',
      categoryLabel: 'Internship',
      format: 'PDF',
      size: '2.1 MB',
      updatedAt: 'May 12, 2026',
      status: 'VERIFIED',
      description: 'Signed agreement regarding intellectual property, confidentiality, and data safety.'
    },
    {
      id: 'doc-3',
      title: 'Digital Intern ID Badge & Access Pass',
      category: 'INTERNSHIP',
      categoryLabel: 'Internship',
      format: 'PNG',
      size: '640 KB',
      updatedAt: 'May 15, 2026',
      status: 'VERIFIED',
      description: 'Accredited digital badge with QR code for building access and event check-in.'
    },

    // Company Documents
    {
      id: 'doc-4',
      title: 'Ethiroli Engineering Onboarding Handbook',
      category: 'COMPANY',
      categoryLabel: 'Company Policy',
      format: 'PDF',
      size: '3.8 MB',
      updatedAt: 'May 15, 2026',
      status: 'OFFICIAL',
      description: 'Guidelines on Git workflows, monorepo architecture, coding standards, and PR reviews.'
    },
    {
      id: 'doc-5',
      title: 'Employee Code of Conduct & Remote Work Policy',
      category: 'COMPANY',
      categoryLabel: 'Company Policy',
      format: 'PDF',
      size: '1.1 MB',
      updatedAt: 'May 15, 2026',
      status: 'OFFICIAL',
      description: 'Work hour guidelines, communication etiquette, and professional conduct expectations.'
    },
    {
      id: 'doc-6',
      title: 'Information Security & Data Protection Guidelines',
      category: 'COMPANY',
      categoryLabel: 'Company Policy',
      format: 'PDF',
      size: '890 KB',
      updatedAt: 'May 15, 2026',
      status: 'OFFICIAL',
      description: 'Security policies on secrets management, API key rotation, and client confidentiality.'
    },

    // Training Documents
    {
      id: 'doc-7',
      title: '45-Day Full-Stack Web Curriculum Syllabus',
      category: 'TRAINING',
      categoryLabel: 'Training Material',
      format: 'PDF',
      size: '2.5 MB',
      updatedAt: 'May 16, 2026',
      status: 'OFFICIAL',
      description: 'Complete day-by-day learning roadmap, competencies checklist, and grading rubric.'
    },
    {
      id: 'doc-8',
      title: 'Git & Linux Terminal Cheat Sheet',
      category: 'TRAINING',
      categoryLabel: 'Training Material',
      format: 'PDF',
      size: '450 KB',
      updatedAt: 'May 18, 2026',
      status: 'OFFICIAL',
      description: 'Essential commands for interactive rebase, cherry-pick, conflict resolution, and SSH.'
    },
    {
      id: 'doc-9',
      title: 'React 19 & Redux Toolkit Architecture Cheat Sheet',
      category: 'TRAINING',
      categoryLabel: 'Training Material',
      format: 'PDF',
      size: '620 KB',
      updatedAt: 'May 20, 2026',
      status: 'OFFICIAL',
      description: 'Best practices for custom hooks, slice design, async thunks, and performance tuning.'
    },

    // Personal Documents
    {
      id: 'doc-10',
      title: 'College NOC & Internship Permission Letter',
      category: 'PERSONAL',
      categoryLabel: 'Personal Vault',
      format: 'PDF',
      size: '1.2 MB',
      updatedAt: 'May 14, 2026',
      status: 'VERIFIED',
      description: 'Authorized permission from college department head allowing full-time internship.'
    },
    {
      id: 'doc-11',
      title: 'Candidate Resume & Curriculum Vitae',
      category: 'PERSONAL',
      categoryLabel: 'Personal Vault',
      format: 'PDF',
      size: '520 KB',
      updatedAt: 'May 08, 2026',
      status: 'VERIFIED',
      description: 'Latest profile resume submitted during application.'
    },
    {
      id: 'doc-12',
      title: 'Bank Account & Stipend Remittance Details',
      category: 'PERSONAL',
      categoryLabel: 'Personal Vault',
      format: 'PDF',
      size: '340 KB',
      updatedAt: 'May 18, 2026',
      status: 'PENDING_VERIFICATION',
      description: 'Cancelled cheque and IFSC details for monthly stipend transfer.'
    },

    // Performance Documents
    {
      id: 'doc-13',
      title: 'Mid-Term 360° Performance Evaluation Report',
      category: 'PERFORMANCE',
      categoryLabel: 'Performance',
      format: 'PDF',
      size: '780 KB',
      updatedAt: 'Sep 15, 2026',
      status: 'OFFICIAL',
      description: 'Formal scorecards, mentor remarks, and distinction milestone audit.'
    },
    {
      id: 'doc-14',
      title: 'Letter of Recommendation (LOR)',
      category: 'PERFORMANCE',
      categoryLabel: 'Performance',
      format: 'PDF',
      size: '—',
      updatedAt: 'Scheduled June 30, 2026',
      status: 'ELIGIBLE_ON_COMPLETION',
      description: 'Official recommendation letter from Founder & Engineering Director upon graduation.'
    }
  ];

  const filteredDocs = activeCategory === 'ALL'
    ? documents
    : documents.filter((d) => d.category === activeCategory);

  const getStatusBadge = (status) => {
    switch (status) {
      case 'VERIFIED':
        return <span className="badge bg-success-subtle text-success border border-success-subtle small"><i className="bi bi-patch-check-fill me-1"></i>Verified ✓</span>;
      case 'OFFICIAL':
        return <span className="badge bg-primary-subtle text-primary border border-primary-subtle small"><i className="bi bi-shield-fill-check me-1"></i>Official</span>;
      case 'PENDING_VERIFICATION':
        return <span className="badge bg-warning-subtle text-warning border border-warning-subtle small"><i className="bi bi-hourglass-split me-1"></i>Pending Verification</span>;
      default:
        return <span className="badge bg-secondary-subtle text-secondary border border-secondary-subtle small"><i className="bi bi-lock-fill me-1"></i>Eligible upon completion</span>;
    }
  };

  const handleDownload = (doc) => {
    if (doc.status === 'ELIGIBLE_ON_COMPLETION') {
      setAlert({ type: 'info', text: 'This document will become available for download upon successful internship completion.' });
      return;
    }
    // Actually write the file. This used to only show a success message.
    const filename = `${safeFilename(doc.title, 'document')}-${doc.id}.svg`;
    try {
      downloadDataUri(buildPreviewImage(doc), filename);
      setAlert({ type: 'success', text: `Downloaded "${filename}" to your Downloads folder.` });
    } catch {
      setAlert({ type: 'danger', text: `Could not download "${doc.title}". Please try again.` });
    }
  };

  /** View renders the document on screen as an image instead of downloading it. */
  const handleView = (doc) => {
    if (doc.status === 'ELIGIBLE_ON_COMPLETION') {
      setAlert({ type: 'info', text: 'This document unlocks once your internship is complete.' });
      return;
    }
    setPreviewDoc(doc);
  };

  const handleUploadSubmit = (e) => {
    e.preventDefault();
    setShowUploadModal(false);
    setAlert({ type: 'success', text: 'Personal document uploaded successfully! Verification takes 24-48 hours.' });
  };

  return (
    <AdminPage
      title="Personal Vault & Document Management"
      subtitle="Access official internship contracts, handbooks, personal records, and performance letters"
    >
      <div className="container-fluid px-0">
        {alert.text && (
          <div className={`alert alert-${alert.type} alert-dismissible fade show mb-2`} role="alert">
            <i className="bi bi-check-circle me-2"></i>{alert.text}
            <button type="button" className="btn-close" onClick={() => setAlert({ type: '', text: '' })}></button>
          </div>
        )}

        {/* Vault Categories & Upload Action */}
        <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-2">
          <div className="d-flex gap-2 flex-wrap">
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'ALL' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('ALL')}
            >
              All Documents ({documents.length})
            </button>
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'INTERNSHIP' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('INTERNSHIP')}
            >
              📁 Internship Docs
            </button>
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'COMPANY' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('COMPANY')}
            >
              📁 Company Policies
            </button>
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'TRAINING' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('TRAINING')}
            >
              📁 Training Guides
            </button>
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'PERSONAL' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('PERSONAL')}
            >
              📁 Personal Vault
            </button>
            <button
              type="button"
              className={`btn btn-sm ${activeCategory === 'PERFORMANCE' ? 'btn-primary' : 'btn-outline-secondary'}`}
              onClick={() => setActiveCategory('PERFORMANCE')}
            >
              📁 Performance
            </button>
          </div>

          <button
            type="button"
            className="btn btn-primary btn-sm d-inline-flex align-items-center gap-1 shadow-sm"
            onClick={() => setShowUploadModal(true)}
          >
            <i className="bi bi-cloud-arrow-up-fill"></i> Upload Personal Document
          </button>
        </div>

        {/* Documents Grid */}
        <div className="row g-4">
          {filteredDocs.map((doc) => (
            <div key={doc.id} className="col-md-6 col-xl-4">
              <div className="card shadow-sm border-0 h-100">
                <div className="card-body p-3 d-flex flex-column">
                  {/* Stacked, not justify-content-between: a long status such
                      as "Pending Verification" needs a line of its own or it
                      spills out past the card edge. */}
                  <div className="d-flex flex-column align-items-start gap-2 mb-3">
                    <span className="badge bg-light text-secondary border small">{doc.categoryLabel}</span>
                    {getStatusBadge(doc.status)}
                  </div>

                  <h6 className="fw-bold mb-2 text-dark">{doc.title}</h6>
                  <p className="text-muted small mb-3 flex-grow-1">{doc.description}</p>

                  <div className="d-flex flex-wrap justify-content-between align-items-center gap-2 text-muted small border-top pt-2 mb-3">
                    <span><i className="bi bi-file-earmark-pdf me-1"></i>{doc.format} • {doc.size}</span>
                    <span>Updated: {doc.updatedAt}</span>
                  </div>

                  <div className="d-flex gap-2 mt-auto">
                    <button
                      className="btn btn-outline-primary flex-grow-1 d-flex align-items-center justify-content-center gap-2"
                      style={{ minHeight: '42px', fontSize: '0.875rem', fontWeight: 600 }}
                      onClick={() => handleView(doc)}
                    >
                      <i className="bi bi-eye" />
                      View
                    </button>
                    <button
                      className="btn btn-primary flex-grow-1 d-flex align-items-center justify-content-center gap-2"
                      style={{ minHeight: '42px', fontSize: '0.875rem', fontWeight: 600 }}
                      onClick={() => handleDownload(doc)}
                      disabled={doc.status === 'ELIGIBLE_ON_COMPLETION'}
                    >
                      <i className="bi bi-download" />
                      Download
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* On-screen document preview. Clicking View opens this instead of
            downloading the file, so the document is readable in place. */}
        {previewDoc && (
          <div
            className="modal show d-block"
            style={{ backgroundColor: 'rgba(0,0,0,0.75)' }}
            tabIndex="-1"
            role="dialog"
            aria-modal="true"
            aria-labelledby="docPreviewTitle"
            onClick={(e) => { if (e.target === e.currentTarget) setPreviewDoc(null); }}
          >
            <div className="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
              <div className="modal-content border-0 shadow">
                <div className="modal-header align-items-center">
                  <div className="min-w-0">
                    <h5 className="modal-title fw-bold mb-0" id="docPreviewTitle">
                      {previewDoc.title}
                    </h5>
                    <small className="text-muted">
                      {previewDoc.format} · {previewDoc.size} · Updated {previewDoc.updatedAt}
                    </small>
                  </div>
                  <div className="d-flex align-items-center gap-2 ms-3">
                    <button
                      type="button"
                      className="btn btn-sm btn-outline-secondary d-none d-sm-inline-flex align-items-center gap-1"
                      onClick={() => handleDownload(previewDoc)}
                    >
                      <i className="bi bi-download" />
                      Download
                    </button>
                    <button
                      type="button"
                      className="btn-close"
                      onClick={() => setPreviewDoc(null)}
                      aria-label="Close preview"
                    />
                  </div>
                </div>
                <div className="modal-body p-0 bg-secondary bg-opacity-10">
                  <div className="d-flex justify-content-center p-3 p-md-4">
                    <img
                      src={buildPreviewImage(previewDoc)}
                      alt={`Preview of ${previewDoc.title}`}
                      className="rounded-3 shadow"
                      style={{ maxWidth: '100%', height: 'auto', maxHeight: '68vh', background: '#fff' }}
                    />
                  </div>
                </div>
                <div className="modal-footer justify-content-between flex-wrap gap-2">
                  <span className="text-muted small">{previewDoc.description}</span>
                  <div className="d-flex gap-2">
                    <button
                      type="button"
                      className="btn btn-sm btn-outline-primary px-3"
                      style={{ minHeight: '38px' }}
                      onClick={() => handleDownload(previewDoc)}
                    >
                      <i className="bi bi-download me-1"></i> Download
                    </button>
                    <button
                      type="button"
                      className="btn btn-sm btn-secondary px-3"
                      style={{ minHeight: '38px' }}
                      onClick={() => setPreviewDoc(null)}
                    >
                      Close
                    </button>
                  </div>
                </div>
                <div className="px-3 pb-3">
                  <ShareBar
                    title={previewDoc.title}
                    text={`${previewDoc.title} — ${previewDoc.categoryLabel} (${previewDoc.format}, ${previewDoc.size}) from the Ethiroli Internship Management System.`}
                    url={`https://ethiroli.net/intern/documents/${previewDoc.id}`}
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Upload Personal Document Modal */}
        {showUploadModal && (
          <div
            className="modal show d-block"
            style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}
            tabIndex="-1"
            role="dialog"
            aria-modal="true"
            aria-label="Upload to Personal Vault"
            onClick={backdropClick(() => setShowUploadModal(false))}
          >
            <div className="modal-dialog modal-dialog-centered modal-dialog-scrollable">
              <div className="modal-content border-0 shadow">
                <div className="modal-header">
                  <h5 className="modal-title fw-bold">Upload to Personal Vault</h5>
                  <button type="button" className="btn-close" onClick={() => setShowUploadModal(false)}></button>
                </div>
                <form onSubmit={handleUploadSubmit}>
                  <div className="modal-body">
                    <div className="mb-3">
                      <label htmlFor="document-type" className="form-label small fw-semibold">Document Type</label>
                      <select id="document-type"
                        className="form-select"
                        value={uploadDocType}
                        onChange={(e) => setUploadDocType(e.target.value)}
                      >
                        <option value="COLLEGE_NOC">College NOC / Permission Letter</option>
                        <option value="RESUME">Updated Resume / CV</option>
                        <option value="GOVT_ID">Government ID (Aadhaar / Passport)</option>
                        <option value="BANK_DETAILS">Bank Details / Cancelled Cheque</option>
                        <option value="DEGREE_PROVISIONAL">Academic Marksheet / Degree</option>
                      </select>
                    </div>

                    <div className="mb-3">
                      <label htmlFor="select-file-pdf-png" className="form-label small fw-semibold">Select File (PDF, PNG, JPG - Max 5MB)</label>
                      <input id="select-file-pdf-png" type="file" className="form-control" accept=".pdf,.png,.jpg,.jpeg" required />
                    </div>

                    <div className="p-3 bg-light rounded-3 border small text-muted">
                      <i className="bi bi-shield-lock-fill text-primary me-1"></i>
                      All documents are encrypted with AES-256 and accessible only by authorized HR & Mentorship coordinators.
                    </div>
                  </div>
                  <div className="modal-footer">
                    <button type="button" className="btn btn-light btn-sm" onClick={() => setShowUploadModal(false)}>
                      Cancel
                    </button>
                    <button type="submit" className="btn btn-primary btn-sm">
                      Upload & Submit for Verification
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        )}
      </div>
    </AdminPage>
  );
}
